# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models

class Operations(models.Model):
    ops_id = models.IntegerField(primary_key=True)
    voyages_id = models.IntegerField(null=True, blank=True)
    vessels_id = models.IntegerField(null=True, blank=True)
    date = models.DateTimeField(null=True, blank=True)
    ops_type = models.CharField(max_length=45, blank=True)
    location = models.CharField(max_length=150, blank=True)
    coords = models.CharField(max_length=60, blank=True)
    bunk_rob = models.DecimalField(null=True, max_digits=7, decimal_places=2, blank=True)
    lo_rob = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    fw_rob = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    mileage = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    transit = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    delays = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    reason = models.CharField(max_length=60, blank=True)
    prospects = models.CharField(max_length=150, blank=True)
    weather_comm = models.CharField(max_length=150, blank=True)
    da = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    final_da = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    balance_da = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    balance_paid = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    docs_received = models.DateTimeField(null=True, blank=True)
    da_comm = models.CharField(max_length=150, blank=True)
    agent = models.CharField(max_length=150, blank=True)
    ctm = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    repair_exp = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    bunk_supply = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    bunk_price = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    bunk_barging = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    bunk_supplier = models.CharField(max_length=150, blank=True)
    lo_supply = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    lo_price = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    lo_barging = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    lo_supplier = models.CharField(max_length=150, blank=True)
    fw_supply = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    fw_price = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    var_exp = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    var_exp_comm = models.TextField(blank=True)
    comment = models.TextField(blank=True)
    frt_received = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    brokerage = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    demurrage = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    due_to_weather = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    due_to_strait = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    due_to_weekend = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    due_to_technical = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    due_to_other = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    delay_comm = models.TextField(blank=True)
    dispatch = models.DecimalField(null=True, max_digits=11, decimal_places=2, blank=True)
    class Meta:
        db_table = u'operations'

class Ports(models.Model):
    id = models.IntegerField(primary_key=True)
    fport = models.CharField(max_length=75, blank=True)
    tport = models.CharField(max_length=75, blank=True)
    region = models.CharField(max_length=21, blank=True)
    distance = models.DecimalField(null=True, max_digits=11, decimal_places=0, blank=True)
    class Meta:
        db_table = u'ports'

class Vessels(models.Model):
    vsl_id = models.IntegerField(primary_key=True)
    vsl_name = models.CharField(max_length=75)
    dwt = models.IntegerField(null=True, blank=True)
    dwcc = models.IntegerField(null=True, blank=True)
    grt = models.IntegerField(null=True, blank=True)
    nrt = models.IntegerField(null=True, blank=True)
    volume = models.IntegerField(null=True, blank=True)
    speed_ballast = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    speed_loaded = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    lo_underway = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    fuel_underway = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    lo_in_port = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    fuel_in_port = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    fw_cons = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    salary = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    pandi = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    loa = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    beam = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    dm = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    draft = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    nav_class = models.IntegerField(null=True, blank=True)
    office_share = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    provisions = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    built = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'vessels'

class Voyages(models.Model):
    voy_id = models.IntegerField(primary_key=True)
    vessels_id = models.IntegerField()
    voy_number = models.CharField(max_length=24)
    charterers = models.TextField(blank=True)
    cargo_type = models.CharField(max_length=90, blank=True)
    loadport1 = models.CharField(max_length=90, blank=True)
    loadport2 = models.CharField(max_length=90, blank=True)
    loadport3 = models.CharField(max_length=90, blank=True)
    dport1 = models.CharField(max_length=90, blank=True)
    dport2 = models.CharField(max_length=90, blank=True)
    dport3 = models.CharField(max_length=90, blank=True)
    strait1 = models.CharField(max_length=90, blank=True)
    strait2 = models.CharField(max_length=90, blank=True)
    strait3 = models.CharField(max_length=90, blank=True)
    start_port = models.CharField(max_length=90, blank=True)
    est_lport1da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_lport2da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_lport3da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_dport1da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_dport2da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_dport3da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_strait1da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_strait2da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_strait3da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_lport1da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_lport2da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_lport3da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_dport1da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_dport2da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_dport3da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_strait1da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_strait2da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_strait3da = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    lport1_agent = models.CharField(max_length=150, blank=True)
    lport2_agent = models.CharField(max_length=150, blank=True)
    lport3_agent = models.CharField(max_length=150, blank=True)
    strait1_agent = models.CharField(max_length=150, blank=True)
    strait2_agent = models.CharField(max_length=150, blank=True)
    strait3_agent = models.CharField(max_length=150, blank=True)
    dport1_agent = models.CharField(max_length=150, blank=True)
    dport2_agent = models.CharField(max_length=150, blank=True)
    dport3_agent = models.CharField(max_length=150, blank=True)
    voyage_start = models.DateTimeField(null=True, blank=True)
    est_voyage_compl = models.DateTimeField(null=True, blank=True)
    act_voyage_compl = models.DateTimeField(null=True, blank=True)
    act_voyage_length = models.DecimalField(null=True, max_digits=20, decimal_places=4, blank=True)
    frt_rate = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    frt_flag = models.IntegerField(null=True, blank=True)
    est_frt = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_frt = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_disb_exp = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_cargo_qty = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_cargo_qty = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_mileage = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_mileage = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_fuel_cons = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_fuel_cons = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_lo_cons = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_lo_cons = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_fuel_cost = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_fuel_cost = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_lo_cost = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_lo_cost = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_go_rob = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_go_price = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    go_sypply1_q = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    go_sypply1_p = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    go_sypply1_b = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    go_sypply1_n = models.CharField(max_length=150, blank=True)
    go_supply1_d = models.DateTimeField(null=True, blank=True)
    go_sypply2_q = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    go_sypply2_p = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    go_sypply2_b = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    go_sypply2_n = models.CharField(max_length=150, blank=True)
    go_supply2_d = models.DateTimeField(null=True, blank=True)
    act_go_rob = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_go_price = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_lo_rob = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_lo_price = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_fw_rob = models.DecimalField(null=True, max_digits=7, decimal_places=2, blank=True)
    lo_sypply1_q = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    lo_sypply1_p = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    lo_sypply1_b = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    lo_sypply1_n = models.CharField(max_length=150, blank=True)
    lo_supply1_d = models.DateTimeField(null=True, blank=True)
    lo_sypply2_q = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    lo_sypply2_p = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    lo_sypply2_b = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    lo_sypply2_n = models.CharField(max_length=150, blank=True)
    lo_supply2_d = models.DateTimeField(null=True, blank=True)
    act_lo_rob = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_lo_price = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_salary = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_salary = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_fw_cons = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_fw_cons = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_fw_cost = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_fw_cost = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    fw_price = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_pni_exp = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_pni_exp = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_office_exp = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    act_office_exp = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    var_exp1 = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    var_exp1_type = models.CharField(max_length=150, blank=True)
    var_exp2 = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    var_exp2_type = models.CharField(max_length=150, blank=True)
    var_exp3 = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    var_exp3_type = models.CharField(max_length=150, blank=True)
    var_exp4 = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    var_exp4_type = models.CharField(max_length=150, blank=True)
    var_exp5 = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    var_exp5_type = models.CharField(max_length=150, blank=True)
    act_speed = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    inv_date = models.DateTimeField(null=True, blank=True)
    is_frt_rcvd = models.IntegerField(null=True, blank=True)
    brokerage = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    est_length = models.DecimalField(null=True, max_digits=20, decimal_places=4, blank=True)
    load_rate = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    disch_rate = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    ets_ballast_leg = models.DecimalField(null=True, max_digits=12, decimal_places=4, blank=True)
    is_inv_issued = models.IntegerField(null=True, blank=True)
    est_days_in_port = models.DecimalField(null=True, max_digits=20, decimal_places=4, blank=True)
    act_days_in_port = models.DecimalField(null=True, max_digits=20, decimal_places=4, blank=True)
    est_days_in_ballast = models.DecimalField(null=True, max_digits=20, decimal_places=4, blank=True)
    act_days_in_ballast = models.DecimalField(null=True, max_digits=20, decimal_places=4, blank=True)
    est_days_underway = models.DecimalField(null=True, max_digits=20, decimal_places=4, blank=True)
    act_days_underway = models.DecimalField(null=True, max_digits=20, decimal_places=4, blank=True)
    performer = models.CharField(max_length=81, blank=True)
    compl_flag = models.IntegerField(null=True, blank=True)
    class Meta:
        db_table = u'voyages'

